Feature/erc1155
swissDAO/daotic pull request #59
Opened 2023-09-11 09:07 UTC by ninuxch

## Description
This PR reviews the code, and gives recommendations on how to improve erc1155.

## What type of PR is this? (check all applicable)

- [x ] 🍕 Feature
- [ x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [x ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

2023-09-11 09:15 UTC, ninuxch commented on src/SwissDAO.sol
>              _attributes = string(
This is not a good solution, much better to return a struct (gas efficiency) and have it convert offline. However, if we can execute this as read only, then it's free.

Also not sure about how much support we get from OpenSea et all for on-chain metadata. Will check this out. (Maybe they support it but it's not a standard.

Usually I prefer to have a metadata URL Web 2.0 style, trustfull. Then have that build the metadata from the contract.

2023-09-11 12:13 UTC, owieth commented on src/SwissDAO.sol
>          } else if (_tokenid == 2) {
I think we can remove this svg encoding function with attributes as soon as the webapp is ready. For displaying user images we anyway have to rely on our webapp to generate that

2023-09-11 16:12 UTC, owieth commented on src/SwissDAO.sol
>          } else if (_tokenid == 2) {
ref: https://github.com/swissDAO/daotic/pull/56

2023-09-13 06:24 UTC, owieth requested changes

2023-09-13 06:24 UTC, owieth commented on src/SwissDAO.sol
> +    uint256 public constant ONBOARDING_BADGE = 110;
In general, I like the idea of the Badges but Onboarding is more of a state to me so we shouldn't use a token for it. I propose to use an enum like this:

```
    enum TokenState {
        ONBOARDING,
        ACTIVE,
        INACTIVE,
        LABS
    }
```

By default it would be ONBOARDING or INACTIVE, then when the user passes the quests, the membership is ACTIVE and eventually with enough points will level up to LABS. What do you guys think? @ninuxch @tomlibert8 

https://github.com/swissDAO/daotic/blob/develop/src/Membership.sol#L78-L83

2023-09-13 17:26 UTC, tomlibert8 commented on src/SwissDAO.sol
> +    uint256 public constant ONBOARDING_BADGE = 110;
I agree that we don't need an onboarding token badge.
I removed it in dc34a83.
And we also don't need the TokenState. Our DAO logic also works without it and I want to keep our contract small. In my opinion, APs reflect how ACTIVE or INACTIVE a specific member is. LABS is a separate entity. Let's discuss it another time.

2023-09-13 17:27 UTC, owieth commented on src/SwissDAO.sol
> +    uint256 public constant ONBOARDING_BADGE = 110;
we need a property or view function that returns the state so we can easily query it and have expressions based on the result

2023-09-13 17:31 UTC, tomlibert8 commented on src/SwissDAO.sol
>              _attributes = string(
Yes, OpenSea supports on-chain metadata if you follow their metadata standards. Even on Sepolia testnet since few weeks.
Yes, gas fees optimization is very important. We are going to deploy it on L2. Looking forward to the gas fee estimation report.

2023-09-13 17:33 UTC, tomlibert8 approved these changes

2023-09-13 17:41 UTC, tomlibert8 approved these changes

2023-09-13 19:28 UTC, tomlibert8 commented
dc34a83

2023-09-13 19:29 UTC, merged